# As of Symfony 5.1.json, deprecations are logged in the dedicated "deprecation" channel when it exists
#monolog:
#    channels: [deprecation]
#    handlers:
#        deprecation:
#            type: stream
#            channels: [deprecation]
#            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
